version: '3.7'
services:
  nginx:
    depends_on:
      - php
    image: openresty/openresty:alpine-fat
    ports:
      - '80:80'
    volumes:
      - ./backend/nginxConf:/etc/nginx/conf.d
      - ./backend:/var/www/html
    restart: always

  php:
    build:
      context: backend
    volumes:
      - ./backend:/var/www/html
    user: root
    restart: always