version: '3.7'
services:
  nginx:
    depends_on:
      - php
    image: openresty/openresty:alpine-fat
    ports:
      - '80:80'
    volumes:
      - ./backend/nginxConf:/etc/nginx/conf.d
      - ./backend:/var/www/html

  php:
    build:
      context: backend
    volumes:
      - ./backend:/var/www/html
      - ./backend/entrypoint.sh:/tmp/entrypoint.sh
    entrypoint: /tmp/entrypoint.sh
    restart: always
    user: root
  front:
    build:
      context: frontend
    ports:
      - '8080:8080'
    volumes:
      - ./frontend:/app